### ISSUE TITLE
Amp not working

### ISSUE THREAD

**Issue by efxtv** [kolappannathan/amp-blogger-templates#7]
I have tried so many wais, amp validator always fails the amp.

**Comment by kolappannathan** [comment]
@efxtv Thank you for pointing it out. It has been a long time since I tested the blog in AMP Validator.  The [new release v20.0.0](https://github.com/kolappannathan/amp-blogger-templates/releases/tag/v20.0.0) should address most of the issues in the validator such as
 - Invalid CSS Properties
 - Duplicate canonical URL
 - Fixed some custom js errors
 - Fixed some style tag errors

However the template will not fully pass the Validation due to limitations with Blogger. For example,
 - The style tags in the error are inserted automatically by Blogger. Some of them such as `b:skin` cannot be removed.
 - The `quickedit `icon which causes 3 errors is part of footer and I don't know how to remove it. I have removed all other quick edit icons.
 - ATOM/XML is a valid MIME type. Ref: [IANA](https://www.iana.org/assignments/media-types/application/atom+xml). But the AMP validator doesn't recognize it.

The main goal when I started this project was to make the blog responsive on mobile along with the images and videos in it.

That said the new version reduces the validation errors by more than half and I will continue to work on improving it. Keep a [watch](https://github.com/kolappannathan/amp-blogger-templates/watchers) on this repo for future releases.
