### ISSUE TITLE
Are you kidding brow

### ISSUE THREAD

**Issue by efxtv** [kolappannathan/amp-blogger-templates#9]
Check your link and your template both are not amp approved. https://amp-blog.kolappan.dev/2020/04/embending-youtube-videos-in-this-amp.html Totally wrong and you should not do like this. Please remove those templates or fix them.

**Comment by kolappannathan** [comment]
@efxtv As mentioned in #7 this template does not pass AMP Validation & some of the validation errors are due to limitations with blogger which I cannot control. I already have multiple blog posts in the demo site explaining the things that are broken, AMP Validation errors, etc... I'll also update the ReadMe and Project description to add this info.

> Please remove those templates or fix them.

If & when I found a way to circumvent these behaviours of Blogger, I will do it. Until then this is the best I can create. I am sharing my work with others. I see no reason to remove them.
